name: Dump Dylib

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Doenload YTLite
        run: |
          wget https://github.com/dayanch96/YTLite/releases/download/v5.2b3/com.dvntm.ytlite_5.2b3_iphoneos-arm64.deb
          
      - name: Install class-dump
        run: brew install class-dump dpkg

      - name: Extract .dylib
        run: |
          dpkg-deb -x com.dvntm.ytlite_5.2b3_iphoneos-arm64.deb ${{ github.workspace }}
          cd ${{ github.workspace }}/var/jb/Library/MobileSubstrate/DynamicLibraries
          cp YTLite.dylib ${{ github.workspace }}

      - name: Dump headers
        run: |
          mkdir headers
          class-dump -arch arm64 -H YTLite.dylib -o headers

      - name: Basic info
        run: |
          file YTLite.dylib > dylib_info.txt
          otool -L YTLite.dylib >> dylib_info.txt
          strings YTLite.dylib > strings.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: analysis
          path: |
            headers
            dylib_info.txt
            strings.txt
